version: '3'

services:
  laravel:
      build:
        context: .
        dockerfile: Dockerfile
      expose:
        - "3000"
      restart: always
      environment:
        VIRTUAL_HOST: assesment.vin.web.id
        LETSENCRYPT_HOST: assesment.vin.web.id
      container_name: assesment.vin.web.id

  mysql:
    image: mysql:8
    command: mysqld --sql_mode=""
    container_name: laravel_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # networks:
    #  - nginx-proxy
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

  composer:
    image: composer:latest
    user: "1000:1000"
    container_name: laravel_composer
    volumes:
      - ./src:/var/www/html
    working_dir: .
    depends_on:
      - laravel
    # networks:
    #  - nginx-proxy

  npm:
    image: node:16
    container_name: laravel_npm
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: .
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: .
    entrypoint: ['php', '/var/www/html/artisan']
    # networks:
    #  - nginx-proxy

networks:
  default:
    external:
      name: nginx-proxy