version: '3'

services:
    laravel:
        build:
          context: .
          dockerfile: Dockerfile
        expose:
          - "3000"
        restart: always
        environment:
          VIRTUAL_HOST: assesment.vin.web.id
          LETSENCRYPT_HOST: assesment.vin.web.id
        container_name: assesment.vin.web.id

networks:
  default:
    external:
      name: nginx-proxy